# Site settings
title: Resource Awareness Philly
email: ramjacvp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Resource Awareness Philly
baseurl: "/homeless-services"
url: "http://ramjac.github.io"
github_username:  ramjac
permalink: /blog/:year/:title/

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index

